
"""
Report Routes
"""

import os

from flask import Blueprint, send_file, jsonify

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

report_bp = Blueprint(
    "report",
    __name__
)

REPORT_FOLDER = "reports"

os.makedirs(REPORT_FOLDER, exist_ok=True)


@report_bp.route(
    "/report",
    methods=["GET"]
)
def generate_report():

    try:

        pdf_path = os.path.join(
            REPORT_FOLDER,
            "Prediction_Report.pdf"
        )

        pdf = canvas.Canvas(
            pdf_path,
            pagesize=letter
        )

        pdf.setTitle("BloodPrint AI Report")

        pdf.setFont("Helvetica-Bold", 20)

        pdf.drawString(
            150,
            760,
            "BloodPrint AI"
        )

        pdf.setFont(
            "Helvetica",
            12
        )

        pdf.drawString(
            50,
            720,
            "Fingerprint Blood Group Prediction Report"
        )

        pdf.drawString(
            50,
            690,
            "This report is generated by the BloodPrint AI system."
        )

        pdf.drawString(
            50,
            660,
            "Prediction details can be extended here."
        )

        pdf.save()

        return send_file(
            pdf_path,
            as_attachment=True
        )

    except Exception as error:

        return jsonify({

            "success": False,

            "message": str(error)

        }), 500
